
export const ACTIONS = {
  SET_BOARD: 'SET_BOARD',
  SET_MODE: 'SET_MODE',
  SET_CELL: 'SET_CELL',
  SET_TURN: 'SET_TURN',
  MAKE_MOVE: 'MAKE_MOVE',
  SET_WINNER: 'SET_WINNER'
}

export const MODES = {
  ONLINE_MULTIPLAYER: 'ONLINE_MULTIPLAYER',
  VERSUS_BOT: 'VERSUS_BOT',
  PASS_AND_PLAY: 'PASS_AND_PLAY'
}

export const SIGNS = {
  X: 'X',
  O: 'O',
  EMPTY: '_'
}